const options = {
    firstInput: [
        "Comercio electrónico",
        "Automóviles e Indumotoras",
        "Servicios basicos agua luz electricidad etc",
        "Bancos y empresas financieras",
        "Aseguradoras",
        "Transporte",
        "Tiendas comerciales y retail",
        "Entretenimiento y turismo",
        "Salud (hospitales, clínicas, etc.)",
        "Educación",
        "Telecomunicaciones",
        "Publicidad engañosa",
        "Servicios básicos, agua, luz, electricidad, etc.",
        "Retención de documentos oficiales",
        "Agresiones y Riñas",
        "Tráfico de Drogas",
        "Secuestros",
        "Aborto",
        "Abuso Sexual y Violación",
        "Homicidios",
        "Manejo en estado de ebriedad",
        "Sustracción de menores  ",
        "Estafas y Delitos económicos",
        "Alcoholímetro",
        "Discriminación y Delitos de odio",
        "Amenazas y extorsiones (chantajes)",
        "Accidentes de Tránsito",
        "Orden de restricción",
        "Amparos",
        "Injurias y Calumnias",
        "Setencias",
        "Fianzas",
        "Delitos Informáticos",
        "Fraude y Abuso de Confianza",
        "Robo de Identidad",
        "Deudas y Embargos",
        "Matrimonio",
        "Compra y Arriendo de Propiedades",
        "Pago de Honorarios",
        "Negligencia médica",
        "Acoso e Intimidación",
        "Bienes mancomunados",
        "Bienes separados",
        "Conflictos vecinales",
        "Arrendamiento",
        "Herencia y Posesiones Efectivas",
        "Inmigración",
        "Vecinos Molestos",
        "Daños y perjuicios",
        "Registro Civil",
        "Desalojos",
        "Mascotas",
        "Incumplimiento de Contrato",
        "Poder",
        "Testamento",
        "Compraventa de inmuebles",
        "Juicio o reconocimiento de Paternidad",
        "Régimen de Visitas",
        "Tuición o tutela",
        "Violencia Intrafamiliar",
        "Custodia",
        "Adopciones",
        "Declaración de Interdicción",
        "Manutención",
        "Divorcio",
        "Concubinato",
        "Emancipación",
        "Pensión Alimenticia",
        "Cambio de Nombre",
        "Abandono de menor",
        "Capitulaciones matrimoniales",
        "Defensa de Derechos Laborales",
        "Accidentes Laborales",
        "Acoso Sexual",
        "Jubilación",
        "Renuncia Voluntaria",
        "Constitución y Asesoría de Sindicatos",
        "Despido Injustificado",
        "Negociación Colectiva",
        "Conciliación laboral",
        "Desaparición de Outsourcing",
        "Acoso laboral",
        "Liquidación ",
        "Finiquitos",
        "Compensaciones",
        "Insolvencia y Quiebras",
        "Redacción o revisión de contratos",
        "Juicios mercantiles",
        "Inversión Extranjera",
        "Contratos comerciales internacionales",
        "Importaciones, exportaciones y derecho aduanero",
        "Recursos Naturales y Medioambientales",
        "Cesión de derechos",
        "Constitución de Sociedades",
        "Clausura y suspensión de servicios",
        "Marcas, Patentes y Propiedad Intelectual - Derecho Comercial",
        "Conflictos con usuarios",
        "Mercado de Capitales",
        "Aval (Responsabilidad)",
        "Incautación de mercancias",
        "Detención ilegal por parte del Estado",
        "Lesiones por parte del Estado",
        "Torturas por parte del Estado",
        "Adopciones irregulares por parte del Estado",
        "Venta irregular de propiedades por parte del Estado",
        "Secuestro por parte del Estado",
        "Sustracción de menores por parte del Estado",
        "Violencia sexual por parte del Estado",
        "Homicidio por parte del Estado",
        "Condonación de impuestos",
        "Defensa fiscal",
        "Planificación Tributaria",
        "Litigios Tributarios",
        "Devoluciones",
        "Pensiones del seguro social",
        "Seguro de Vida",
        "Certificación y titulación",
        "Acoso Digital",
        "Venta ilegal de datos personales",
        "Deportación",
        "Trámite de naturalización",
        "Registro de marcas",
        "Licencias de uso",
        "Registro de obras músicales y literarias",
        "Regalías",
        "Fraude electoral",
        "Compraventas de Inmuebles con o sin Garantía Hipotecaria y/o Fiduciaria",
        "Cancelaciones de Hipotecas  y Reserva de Dominio",
        "Donaciones",
        "Adjudicaciones por Herencia",
        "Adjudicaciones por Remate Judicial",
        "Fideicomisos, Traslativas de Administración o de Garantía",
        "Lotificaciones y Relotificaciones de Predios",
        "Subdivisión y Fusión de Predios",
        "Constitución de Sociedades Mercantiles y Civiles",
        "Inscripción al RFC en la constitución de Sociedades",
        "Protocolización de Actas de Asambleas y Juntas",
        "Protocolización de Actas de Asambleas y Juntas",
        "Otorgamiento y Revocación de Poderes",
        "Testamentos",
        "Sucesiones testamentarias e intestamentariasa",
        "Ratificaciones de firmas",
        "Fe de hechos",
        "Notificaciones",
        "Requerimientos",
        "Interpelaciones",
        "Cotejos"
    ],
    secondInput: [
        "Anti corrupción",
        "Amparo",
        "Comercio internacional",
        "Compliance",
        "Derecho civil",
        "Derecho penal",
        "Derecho mercantil",
        "Derecho familiar",
        "Derecho laboral",
        "Derecho de seguridad social",
        "Derecho constitucional",
        "Derechos humanos",
        "Derecho fiscal",
        "Derecho administrativo",
        "Derecho corporativo",
        "Derecho de la propiedad intelectual",
        "Derecho energético",
        "Derecho en telecomunicaciones",
        "Defensa del consumidor",
        "Derecho aduanero",
        "Derecho agrario",
        "Derecho ambiental",
        "Derecho migratorio",
        "Derecho bancario",
        "Derecho canónico",
        "Derecho deportivo",
        "Derecho educativo",
        "Derecho electoral",
        "Derecho informático",
        "Derecho inmobiliario",
        "Derecho marítimo y aeronáutico",
        "Legislación médica",
        "Derecho militar",
        "Derecho minero y petrolero",
        "Derecho municipal",
        "Derecho tributario",
        "Derecho urbanístico",
        "Derecho de sociedades",
        "Fusiones y adquisiciones",
        "Negligencia médica",
        "Norma 035",
        "Mediación y arbitraje",
        "Mercado de capitales",
        "Negligencias legales",
        "Propiedad industrial",
        "Propiedad intelectual",
        "Corredores públicos",
        "Peritos contables",
        "Peritos traductores",
        "Peritos valuadores",
        "Prevención de lavado",
        "Protección de datos personales",
        "Seguros / Fianzas",
        "Trámites ante el IMPI",
        "Ley General de Sociedades Mercantiles",
        "Responsabilidad administrativa",
        "Derecho empresarial y corporativo",
        "Normas jurídicas empresariales",
        "Acceso a la educación gratuita (Preescolar, Primaria, Secundaria y Media superior)",
        "Libertad de tránsito (Derechos la libertad de tránsito)",
        "Separaciones y divorcios de mutuo acuerdo o contenciosos.",
        "Derecho de propiedad y otros derechos reales",
        "Derechos laborales",
        "Delitos dolosos y culposos",
        "Desalojos (Forzoso, morosidad e incausado)",
        "Menores (Patria potestad, guarda y custodia, pensiones alimenticias, régimen de visitas)",
        "Contratos comerciales internacionales",
        "Responsabilidad civil por daños y perjuicios",
        "Cobranza judicial y extrajudicial de cartera vencida",
        "Recuperación de créditos bancarios",
        "Solución de conflictos entre accionistas",
        "Rescisión y ejecución de contratos y convenios mercantiles",
        "Juicios Concursales",
        "Cumplimiento Normativo",
        "Aviso de Privacidad de Datos Personales ante INAI",
        "Permisos de Trabajo de Extranjeros ante INM",
        "Informes Corporativos ante SE",
        "Contrato Colectivo de Trabajo (Sindicato)",
        "Due Diligence",
        "Contabilidad",
        "Cumplimiento de Obligaciones Fiscales",
        "Estados Financieros",
        "Cálculo de Impuestos Locales y Federales",
        "Nómina",
        "Consultoría y Planeación Fiscal",
        "Precios de Transferencia",
        "Valuación de Acciones",
        "Dictamen Fiscal y Financiero",
        "Créditos fiscales y multas",
        "Cancelación de sellos digitales",
        "Congelamiento de cuentas bancarias",
        "Embargo de bienes e intervención de negociaciones",
        "Negativas de devolución de impuestos",
        "Determinación de contribuciones de Comercio Exterior",
        "Libros Sociales",
        "Poder",
        "Testamento",
        "Actas de asamblea",
        "Donaciones de Acciones",
        "Compraventa de inmuebles",
        "Secretaría Corporativa",
        "Servicios Notariales",
        "Estructura de Estatutos Sociales",
        "Emisión de Títulos de Acciones y/o",
        "Certificados de Aportación",
        "Asambleas Ordinarias y Extraordinarias de Accionistas",
    ],
    estados: [
        "Aguascalientes",
        "Baja California",
        "Baja California Sur",
        "Campeche",
        "Chiapas",
        "Chihuahua",
        "CDMX",
        "Coahuila de Zaragoza",
        "Colima",
        "Durango",
        "Estado de México",
        "Guanajuato",
        "Guerrero",
        "Hidalgo",
        "Jalisco",
        "Michoacán de Ocampo",
        "Morelos",
        "Nayarit",
        "Nuevo León",
        "Oaxaca",
        "Puebla",
        "Querétaro",
        "Quintana Roo",
        "San Luis Potosí",
        "Sinaloa",
        "Sonora",
        "Tabasco",
        "Tamaulipas",
        "Tlaxcala",
        "Veracruz de Ignacio de la Llave",
        "Yucatán",
        "Zacatecas",
    ]
}

const form = document.querySelector(".form form");
console.log(form);
form.addEventListener("keyup", e =>{

    e.target.setAttribute("list","list");

    let array =[]
    if (e.target.dataset.type=="firstInput") {
        array =  options.firstInput
    } else if (e.target.dataset.type=="secondInput") {
        array =  options.secondInput
    } else if (e.target.dataset.type=="estados") {
        array =  options.estados
    } else {
        return
    }

    document.getElementById("list").innerHTML="";
    array.map(a =>{
        document.getElementById("list").innerHTML+=`<option value="${a}">`
    })

})





